export interface DrinkDetailsView {
  detailsTitleEN: string
  detailsTitleES: string
  detailsTitleDE: string
  detailsTitleFR: string
  detailsTitleIT: string
  detailsCategoryEN: string
  detailsCategoryES: string
  detailsCategoryDE: string
  detailsCategoryFR: string
  detailsCategoryIT: string
  detailsAlcoholicEN: string
  detailsAlcoholicES: string
  detailsAlcoholicDE: string
  detailsAlcoholicFR: string
  detailsAlcoholicIT: string
  detailsGlassEN: string
  detailsGlassES: string
  detailsGlassDE: string
  detailsGlassFR: string
  detailsGlassIT: string
  detailsIngredientsEN: string
  detailsIngredientsES: string
  detailsIngredientsDE: string
  detailsIngredientsFR: string
  detailsIngredientsIT: string
  detailsInstructionsEN: string
  detailsInstructionsES: string
  detailsInstructionsDE: string
  detailsInstructionsFR: string
  detailsInstructionsIT: string
  goToBtnEN: string
  goToBtnES: string
  goToBtnDE: string
  goToBtnFR: string
  goToBtnIT: string
  AlcoholicDrinksBtnEN: string
  AlcoholicDrinksBtnES: string
  AlcoholicDrinksBtnDE: string
  AlcoholicDrinksBtnFR: string
  AlcoholicDrinksBtnIT: string
  NonAlcoholicDrinksBtnEN: string
  NonAlcoholicDrinksBtnES: string
  NonAlcoholicDrinksBtnDE: string
  NonAlcoholicDrinksBtnFR: string
  NonAlcoholicDrinksBtnIT: string
  RandomDrinksBtnEN: string
  RandomDrinksBtnES: string
  RandomDrinksBtnDE: string
  RandomDrinksBtnFR: string
  RandomDrinksBtnIT: string
  loadingEN: string
  loadingES: string
  loadingDE: string
  loadingFR: string
  loadingIT: string
  noTranslationEN: string
  noTranslationES: string
  noTranslationDE: string
  noTranslationFR: string
  noTranslationIT: string
  noInstructionsEN: string
  noInstructionsES: string
  noInstructionsDE: string
  noInstructionsFR: string
  noInstructionsIT: string
  noDataEN: string
  noDataES: string
  noDataDE: string
  noDataFR: string
  noDataIT: string
}
