export interface RandomDrinkView {
  randomTitlePageEN: string
  randomTitlePageES: string
  randomTitlePageDE: string
  randomTitlePageFR: string
  randomTitlePageIT: string
  randomRefreshBtnEN: string
  randomRefreshBtnES: string
  randomRefreshBtnDE: string
  randomRefreshBtnFR: string
  randomRefreshBtnIT: string
  randomCategoryEN: string
  randomCategoryES: string
  randomCategoryDE: string
  randomCategoryFR: string
  randomCategoryIT: string
  randomAlcoholicEN: string
  randomAlcoholicES: string
  randomAlcoholicDE: string
  randomAlcoholicFR: string
  randomAlcoholicIT: string
  randomGlassEN: string
  randomGlassES: string
  randomGlassDE: string
  randomGlassFR: string
  randomGlassIT: string
  randomIngredientsEN: string
  randomIngredientsES: string
  randomIngredientsDE: string
  randomIngredientsFR: string
  randomIngredientsIT: string
  randomInstructionsEN: string
  randomInstructionsES: string
  randomInstructionsDE: string
  randomInstructionsFR: string
  randomInstructionsIT: string
  goToBtnEN: string
  goToBtnES: string
  goToBtnDE: string
  goToBtnFR: string
  goToBtnIT: string
  AlcoholicDrinksBtnEN: string
  AlcoholicDrinksBtnES: string
  AlcoholicDrinksBtnDE: string
  AlcoholicDrinksBtnFR: string
  AlcoholicDrinksBtnIT: string
  NonAlcoholicDrinksBtnEN: string
  NonAlcoholicDrinksBtnES: string
  NonAlcoholicDrinksBtnDE: string
  NonAlcoholicDrinksBtnFR: string
  NonAlcoholicDrinksBtnIT: string
  loadingEN: string
  loadingES: string
  loadingDE: string
  loadingFR: string
  loadingIT: string
  noTranslationEN: string
  noTranslationES: string
  noTranslationDE: string
  noTranslationFR: string
  noTranslationIT: string
  noInstructionsEN: string
  noInstructionsES: string
  noInstructionsDE: string
  noInstructionsFR: string
  noInstructionsIT: string
  noDataEN: string
  noDataES: string
  noDataDE: string
  noDataFR: string
  noDataIT: string
}
